# Hoán vị

Cho tập hợp:

$$
A = \{1, 2, 3, \ldots, n\}
$$

Một **hoán vị** của \(n\) phần tử là một cách sắp xếp \(n\) phần tử đó theo một thứ tự nhất định.

Số hoán vị của \(n\) phần tử là:

$$
n!
$$

Ví dụ, với:

$$
A = \{1, 2, 3\}
$$

Các hoán vị của \(A\) là:

$$
(1,2,3),\ (1,3,2),\ (2,1,3),\ (2,3,1),\ (3,1,2),\ (3,2,1)
$$

Vậy số hoán vị là:

$$
3! = 6
$$

---

# Nghịch thế

Xét một hoán vị:

$$
(j_1, j_2, \ldots, j_n)
$$

Một **nghịch thế** là một cặp phần tử:

$$
(j_h, j_k)
$$

thỏa mãn đồng thời hai điều kiện:

$$
j_h > j_k
$$

và

$$
h < k
$$

Nói cách khác, trong hoán vị, nếu một số lớn đứng trước một số nhỏ thì cặp đó được gọi là một nghịch thế.

In [4]:
# tính số nghịch thế của n số nguyên dương khác nhau
def count_inversions(p):
    n = len(p)
    count = 0

    for h in range(n):
        for k in range(h + 1, n):
            if p[h] > p[k]:
                count += 1

    return count

p = [1, 3, 5, 2, 4]
p2 = [3,4,5,1,2]

print(count_inversions(p))
print(count_inversions(p2))

3
6


# Định thức

Xét ma trận vuông cấp \(n\):

$$
A = (a_{ij})_{n \times n}
$$

Định thức của ma trận \(A\) được ký hiệu là:

$$
\det(A)
$$

hoặc:

$$
|A|
$$

Công thức tổng quát của định thức là:

$$
\det(A)
=
|A|
=
\sum_{(j_1, j_2, \ldots, j_n)}
(-1)^{N(j_1, j_2, \ldots, j_n)}
a_{1j_1}a_{2j_2}\cdots a_{nj_n}
$$

Trong đó:

Thứ nhất, dãy chỉ số

$$
(j_1, j_2, \ldots, j_n)
$$

là một hoán vị của tập

$$
\{1, 2, \ldots, n\}
$$

Thứ hai,

$$
N(j_1, j_2, \ldots, j_n)
$$

là số nghịch thế của hoán vị

$$
(j_1, j_2, \ldots, j_n)
$$

Thứ ba, biểu thức

$$
a_{1j_1}a_{2j_2}\cdots a_{nj_n}
$$

là tích của \(n\) phần tử, mỗi phần tử lấy từ một dòng khác nhau và một cột khác nhau của ma trận

$$
A
$$

In [7]:
import numpy as np
A = np.array([[1, 4, 7], [2, 5, 8], [3, 6, 9]])
print(A)
det_A = np.linalg.det(A)
print(det_A)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
0.0


$$
\begin{vmatrix}
1 & 1 & 1 \\
4 & 5 & x + 11 \\
3 & 4 & 10
\end{vmatrix}
= 2
$$



In [ ]:
import sympy as sp

# Khai báo biến x
x = sp.symbols('x')

# Khai báo ma trận
A = sp.Matrix([
    [1, 1, 1],
    [4, 5, x + 11],
    [3, 4, 10]
])

# Tính định thức
det_A = A.det()

print("Định thức của A là:")
print(det_A)

# Giải phương trình det(A) = 2
solution = sp.solve(sp.Eq(det_A, 2), x)

print("Nghiệm x là:")
print(solution)

Định thức của A là:
-x
Nghiệm x là:
[-2]


$$
\begin{vmatrix}
1 & x & 2 \\
1 & 1 & 2*x \\
1 & 2 & x
\end{vmatrix}
= 0
$$

In [10]:
x = sp.symbols('x')

A = sp.Matrix([
    [1, x, 2],
    [1, 1, 2*x],
    [1, 2, x]
])
det_A = A.det()
sp.solve(sp.Eq(det_A,0), x)

[1, 2]