Kiểm tra tập đa thức sau là **độc lập tuyến tính** hay **phụ thuộc tuyến tính** trong không gian \(P_2\):

$$
S=\{\,2-x,\;2x-x^2,\;6-5x+x^2\,\}\subset P_2
$$

Ta chuyển các đa thức trong \(S\) về vector hệ số theo cơ sở chuẩn của \(P_2\):

$$
\{1, x, x^2\}
$$

Với:

$$
p_1(x)=2-x=2-1x+0x^2
$$

$$
p_2(x)=2x-x^2=0+2x-1x^2
$$

$$
p_3(x)=6-5x+x^2=6-5x+1x^2
$$

Ta có các vector hệ số:

$$
p_1=
\begin{bmatrix}
2\\
-1\\
0
\end{bmatrix},
\quad
p_2=
\begin{bmatrix}
0\\
2\\
-1
\end{bmatrix},
\quad
p_3=
\begin{bmatrix}
6\\
-5\\
1
\end{bmatrix}
$$

Lập ma trận \(A\) bằng cách lấy các vector hệ số làm các cột:

$$
A=
\begin{bmatrix}
2 & 0 & 6\\
-1 & 2 & -5\\
0 & -1 & 1
\end{bmatrix}
$$

In [ ]:
import sympy as sp

A = sp.Matrix([
    [2, 0, 6],
    [-1, 2, -5],
    [0, -1, 1]
])

det_A = A.det()

print(det_A)

0


Kiểm tra hệ ma trận sau là **độc lập tuyến tính** hay **phụ thuộc tuyến tính** trong không gian \(M_{2 \times 2}\):

$$
S_1=
\begin{bmatrix}
6 & 2\\
1 & 0
\end{bmatrix},
\quad
S_2=
\begin{bmatrix}
1 & 1\\
1 & 0
\end{bmatrix}
$$

$$
S_3=
\begin{bmatrix}
1 & 1\\
0 & 0
\end{bmatrix},
\quad
S_4=
\begin{bmatrix}
4 & 0\\
0 & 0
\end{bmatrix}
$$

Trong đó:

$$
S=\{S_1,S_2,S_3,S_4\}\subset M_{2 \times 2}
$$

Về bản chất, ta làm như sau:

**Bước 1:** Làm phẳng từng ma trận \(S_1, S_2, S_3, S_4\) thành vector.

Ví dụ:

$$
S_1=
\begin{bmatrix}
6 & 2\\
1 & 0
\end{bmatrix}
$$

Làm phẳng theo thứ tự từng hàng:

$$
S_1
\rightarrow
\begin{bmatrix}
6\\
2\\
1\\
0
\end{bmatrix}
$$

Tương tự:

$$
S_2=
\begin{bmatrix}
1 & 1\\
1 & 0
\end{bmatrix}
\rightarrow
\begin{bmatrix}
1\\
1\\
1\\
0
\end{bmatrix}
$$

$$
S_3=
\begin{bmatrix}
1 & 1\\
0 & 0
\end{bmatrix}
\rightarrow
\begin{bmatrix}
1\\
1\\
0\\
0
\end{bmatrix}
$$

$$
S_4=
\begin{bmatrix}
4 & 0\\
0 & 0
\end{bmatrix}
\rightarrow
\begin{bmatrix}
4\\
0\\
0\\
0
\end{bmatrix}
$$

**Bước 2:** Xếp các vector vừa tạo vào làm các cột của ma trận \(A\).

$$
A=
\begin{bmatrix}
| & | & | & |\\
S_1 & S_2 & S_3 & S_4\\
| & | & | & |
\end{bmatrix}
$$

Cụ thể:

$$
A=
\begin{bmatrix}
6 & 1 & 1 & 4\\
2 & 1 & 1 & 0\\
1 & 1 & 0 & 0\\
0 & 0 & 0 & 0
\end{bmatrix}
$$

**Bước 3:** Tính định thức của ma trận \(A\).

$$
\det(A)=0
$$

Vì:

$$
\det(A)=0
$$

nên các cột của \(A\) phụ thuộc tuyến tính.

Do đó:

$$
\boxed{
S_1,S_2,S_3,S_4 \text{ phụ thuộc tuyến tính}
}
$$

In [5]:

import numpy as np
# kiểm tra 4 ma trận 2×2 có độc lập tuyến tính (linearly independent) hay phụ thuộc tuyến tính (linearly dependent) trong không gian các ma trận M 2×2

S1 = np.array([[6, 2], [1, 0]])
S2 = np.array([[1, 1], [1, 0]])
S3 = np.array([[1, 1], [0, 0]])
S4 = np.array([[4, 0], [0, 0]])
# tao ma tran A tu 4 ma tran S1, S2, S3, S4
A = np.array([[6,1,1,4], [2,1,1,0], [1,1,0,0], [0,0,0,0]])
# tinh dinh thuc cua ma tran A
det_A = np.linalg.det(A)
print(det_A)


0.0


## Bài tập 2

Kiểm tra tập vector sau là **độc lập tuyến tính** hay **phụ thuộc tuyến tính** trong không gian \(\mathbb{C}^4\):

$$
S=\left\{
(1,0,1,0),\;
(2,0,1,2),\;
(2,0,2,4)
\right\}
\subset \mathbb{C}^4
$$

## Lời giải

Ta có tập vector:

$$
S=\left\{
(1,0,1,0),\;
(2,0,1,2),\;
(2,0,2,4)
\right\}
\subset \mathbb{C}^4
$$

Gọi:

$$
v_1=(1,0,1,0)
$$

$$
v_2=(2,0,1,2)
$$

$$
v_3=(2,0,2,4)
$$

Ta cần kiểm tra xem phương trình:

$$
a v_1 + b v_2 + c v_3 = 0
$$

có nghiệm không tầm thường hay không.

Nếu phương trình chỉ có nghiệm:

$$
a=b=c=0
$$

thì tập \(S\) **độc lập tuyến tính**.

Nếu tồn tại nghiệm không đồng thời bằng \(0\), thì tập \(S\) **phụ thuộc tuyến tính**.

---

Ta xếp các vector \(v_1,v_2,v_3\) thành các cột của ma trận \(A\):

$$
A=
\begin{bmatrix}
1 & 2 & 2\\
0 & 0 & 0\\
1 & 1 & 2\\
0 & 2 & 4
\end{bmatrix}
$$

Ma trận \(A\) có kích thước \(4 \times 3\), không phải ma trận vuông, nên không tính được trực tiếp \(\det(A)\).

Do đó, ta kiểm tra bằng hạng ma trận:

$$
rank(A)
$$

Nguyên tắc kiểm tra:

$$
rank(A)=\text{số vector}
$$

thì các vector độc lập tuyến tính.

Ở đây số vector là \(3\). Vì vậy:

$$
rank(A)=3
\Rightarrow S \text{ độc lập tuyến tính}
$$

$$
rank(A)<3
\Rightarrow S \text{ phụ thuộc tuyến tính}
$$

---

Ta có thể xét một ma trận con \(3 \times 3\) bằng cách lấy các hàng 1, 3, 4 của \(A\):

$$
B=
\begin{bmatrix}
1 & 2 & 2\\
1 & 1 & 2\\
0 & 2 & 4
\end{bmatrix}
$$

Tính định thức:

$$
\det(B)
=
\begin{vmatrix}
1 & 2 & 2\\
1 & 1 & 2\\
0 & 2 & 4
\end{vmatrix}
$$

Khai triển theo hàng đầu tiên:

$$
\det(B)
=
1
\begin{vmatrix}
1 & 2\\
2 & 4
\end{vmatrix}
-
2
\begin{vmatrix}
1 & 2\\
0 & 4
\end{vmatrix}
+
2
\begin{vmatrix}
1 & 1\\
0 & 2
\end{vmatrix}
$$

Tính từng định thức con:

$$
\begin{vmatrix}
1 & 2\\
2 & 4
\end{vmatrix}
=1\cdot 4-2\cdot 2=0
$$

$$
\begin{vmatrix}
1 & 2\\
0 & 4
\end{vmatrix}
=1\cdot 4-2\cdot 0=4
$$

$$
\begin{vmatrix}
1 & 1\\
0 & 2
\end{vmatrix}
=1\cdot 2-1\cdot 0=2
$$

Suy ra:

$$
\det(B)=1\cdot 0-2\cdot 4+2\cdot 2
$$

$$
\det(B)=0-8+4=-4
$$

Vì:

$$
\det(B)=-4\neq 0
$$

nên tồn tại một định thức con cấp \(3\) khác \(0\). Do đó:

$$
rank(A)=3
$$

Mà số vector trong \(S\) là \(3\), nên:

$$
rank(A)=3
$$

Suy ra:

$$
\boxed{
S \text{ độc lập tuyến tính}
}
$$

In [13]:
import numpy as np

v1 = np.array([1, 0, 1, 0])
v2 = np.array([2, 0, 1, 2])
v3 = np.array([2, 0, 2, 4])

A = np.column_stack([v1, v2, v3])

rank_A = np.linalg.matrix_rank(A)

print(A)
print("rank(A) =", rank_A)

if rank_A == 3:
    print("S độc lập tuyến tính")
else:
    print("S phụ thuộc tuyến tính")

[[1 2 2]
 [0 0 0]
 [1 1 2]
 [0 2 4]]
rank(A) = 3
S độc lập tuyến tính


In [16]:
import numpy as np

v1 = np.array([[1, -1], [4, 5]])
v2 = np.array([[4, 3], [-2, 3]])
v3 = np.array([[1, -8], [22, 23]])

# Làm phẳng từng ma trận thành vector 4 chiều
v1_flat = v1.flatten()
v2_flat = v2.flatten()
v3_flat = v3.flatten()

# Xếp các vector thành các cột của ma trận A
A = np.column_stack([v1_flat, v2_flat, v3_flat])

rank_A = np.linalg.matrix_rank(A)

print(A)
print("rank(A) =", rank_A)

if rank_A == 3:
    print("S độc lập tuyến tính")
else:
    print("S phụ thuộc tuyến tính")

[[ 1  4  1]
 [-1  3 -8]
 [ 4 -2 22]
 [ 5  3 23]]
rank(A) = 3
S độc lập tuyến tính


In [18]:
import sympy as sp
m = sp.symbols('m')
A = sp.Matrix([
    [1, -1, 1],
    [2, m, 4+ m],
    [m, -2, 2*m-2]
])
det_A = A.det()
det_A_simplified = sp.simplify(det_A)
print(det_A_simplified)

0
