# Phép cộng hai ma trận

$$
(a_{ij})_{m \times n} + (b_{ij})_{m \times n}
=
(a_{ij} + b_{ij})_{m \times n}
$$

# Phép nhân ma trận với một số

$$
K(a_{ij})_{m \times n}
=
(Ka_{ij})_{m \times n}
$$

#### Phép nhân hai ma trận

Cho hai ma trận:

$$
A = (a_{ij})_{m \times n}
$$

và

$$
B = (b_{jk})_{n \times p}
$$

Khi đó tích của hai ma trận là:

$$
A \times B = C
$$

hay viết theo ký hiệu phần tử:

$$
(a_{ij})_{m \times n} \times (b_{jk})_{n \times p}
=
(c_{ik})_{m \times p}
$$

Trong đó phần tử ở dòng `i`, cột `k` của ma trận kết quả `C` được tính bằng:

$$
c_{ik}
=
\sum_{j=1}^{n} a_{ij} b_{jk}
$$

Diễn giải:

- Ma trận thứ nhất có kích thước `m × n`.
- Ma trận thứ hai có kích thước `n × p`.
- Hai ma trận nhân được với nhau khi số cột của ma trận thứ nhất bằng số dòng của ma trận thứ hai.
- Kết quả là một ma trận mới có kích thước `m × p`.
- Mỗi phần tử `c_{ik}` được tính bằng cách lấy dòng thứ `i` của ma trận `A` nhân tương ứng với cột thứ `k` của ma trận `B`, rồi cộng các tích lại.

In [5]:
import numpy as np

A = np.array([[1,4],
             [2,5],
             [3,6]])

B = np.array([[1,1,1],
             [2,2,2]])

A@B
B@A

array([[ 6, 15],
       [12, 30]])

In [7]:
# su dung vong lap de nhan 2 ma tran
def matrix_multiply(A, B):
    m, n = A.shape
    p, q = B.shape
    if n != p:
        raise ValueError("So cot cua ma tran A phai bang so dong cua ma tran B")
    C = np.zeros((m, q))
    for i in range(m):
        for j in range(q):
            for k in range(n):
                C[i, j] += A[i, k] * B[k, j]
    return C
C = matrix_multiply(A, B)
C

array([[ 9.,  9.,  9.],
       [12., 12., 12.],
       [15., 15., 15.]])

### Nhận xét về phép nhân ma trận

Phép nhân hai ma trận **không có tính chất giao hoán**.

Nói cách khác, trong đa số trường hợp:

$$
AB \ne BA
$$

Điều này có nghĩa là đổi thứ tự nhân hai ma trận có thể làm thay đổi kết quả, hoặc thậm chí một trong hai phép nhân có thể không thực hiện được.

Tuy nhiên, phép nhân ma trận vẫn có **tính chất kết hợp**:

$$
(AB)C = A(BC)
$$

Miễn là các kích thước của ma trận phù hợp để thực hiện phép nhân.

### Chú ý liên quan đến ma trận chuyển vị

Với ma trận \(A\), nếu chuyển vị hai lần thì ta thu lại chính ma trận ban đầu:

$$
(A^T)^T = A
$$

Với hai ma trận \(A\) và \(B\) có cùng kích thước, chuyển vị của tổng bằng tổng các chuyển vị:

$$
(A + B)^T = A^T + B^T
$$

Với hai ma trận \(A\) và \(B\) có kích thước phù hợp để nhân được với nhau, chuyển vị của tích bằng tích các chuyển vị theo **thứ tự ngược lại**:

$$
(AB)^T = B^T A^T
$$

### Bài tập: Tìm ma trận \(A\)

Tìm ma trận \(A\), biết rằng:

$$
\left(
2A^T - 3
\begin{pmatrix}
1 & 2 \\
-1 & 1
\end{pmatrix}
\right)^T
=
\begin{pmatrix}
2 & 3 \\
-1 & 2
\end{pmatrix}
$$

In [10]:
import numpy as np

M = np.array([
    [1, 2],
    [-1, 1]
])

B = np.array([
    [2, 3],
    [-1, 2]
])

A_T = (B.T + 3 * M) / 2

A = A_T.T

print("A_T =")
print(A_T)

print("A =")
print(A)

A_T =
[[2.5 2.5]
 [0.  2.5]]
A =
[[2.5 0. ]
 [2.5 2.5]]
